# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b87f171127fa28f0bfe6ffcbecd6280877e4444019a3f3521e33d549459244843d7ec86dbcabb1fc26b6b086e3e05e682a609b7f0e39cf22cff218959b248a64

test:
  secret_key_base: 6eb41cca055177a3dc1d0d9c8aad37a49430b4b7018b7be5aaeed570f468560d0c982059ed0cc512522ec8df225f6af2203fb2a83a4018c43a6fc030ad61047a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
